name: Integration test against news-search-api:main

on:
  - push

jobs:
  fixture-integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    name: Integration test with dummy ES data
    steps:

      # setup ES index
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Run Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.8.2
          security-enabled: false
      - name: Elasticsearch is reachable
        run: |
          curl --verbose --show-error http://localhost:9200
      - name: news-search-api Checkout
        run: |
          docker run -p 8000:8000 mcsystems/news-search-api:main

      # setup news-search-api server and dummy data
      - name: Checkout news-search-api server
        uses: actions/checkout@v4
        with:
          repository: mediacloud/news-search-api
          path: news-search-api
      - name: Install news-search-api server python dependencies
        with:
          path: news-search-api
        run: |
          pip install -e .[dev]
      - name: Install fixtures
        with:
          path: news-search-api
        run: |
          python -m test.create_fixtures
      - name: Run news-search-api server
        with:
          path: news-search-api
        run: |
          python api.py

      # set up this code and run test
      - name: Main checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Install python dependencies
        with:
          path: main
        run: |
          pip install -e .[dev]
      - name: Run integration test
        with:
          path: main
        run: |
          pytest waybacknews/tests/test_fixtures.py
