name: Integration test against news-search-api:main

on:
  - push

jobs:
  fixture-integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    name: Unit tests in Docker
    steps:

      - uses: actions/checkout@v4
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Run Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.8.2
          security-enabled: false
      - name: Elasticsearch is reachable
        run: |
          curl --verbose --show-error http://localhost:9200

      - name: Run news-search-api latest from main
        run: |
          docker run -p 8000:8000 mcsystems/news-search-api:main

      - name: Install python dependencies
        run: |
          pip install -e .[dev]
      - name: Run integration test
        run: |
          pytest waybacknews/tests/test_fixtures.py
